### ISSUE TITLE
Add POST endpoint for finalizing order 

### ISSUE THREAD

**Issue by trezy** [pcww/builder#25]

**Comment by brian-slate** [comment]
Post endpoint exists: http://pinecliffwoodworks.com/wp-json/board-builder/v1/order

Post order model JSON. Example:
`
{"email":"me@here.com","order_date":"2016-10-05 21:04:22","name":"Brian Q. Johnson","estimated_order_amount":"297.36", "board_id":"1"}`

**Comment by brian-slate** [comment]
As discussed @trezy, we need to decide whether we're going to use Mailchimp for sending email or do our own thing.

**Comment by brian-slate** [comment]
Closing in favor of #61
