### ISSUE TITLE
Strips should have an "End Grain" option.

### ISSUE THREAD

**Issue by brian-slate** [pcww/builder#43]
Add additional option to specify "end grain" for the selected strip. For now this wont update the display, but will let Jason know they want end grains. Basically instead of using a regular strip, he will cut off a bunch of ends in the thickness of the board, and point the "butts" up giving it a different look. We can add a message to users and a link to the gallery.

**Comment by voltaaage** [comment]
https://www.craftsy.com/blog/2015/02/how-to-make-an-end-grain-cutting-board/
https://www.craftsy.com/blog/2015/03/maple-end-grain-cutting-board/

Really interesting process to make them. My roommate mentioned that end grains are generally more desirable:

> END GRAIN VS. EDGE GRAIN
> Chefs prefer end grain cutting boards because they have a kind of self-healing feature built in. When a knife blade goes into the board, it separates the wood fibers instead of severing them. That allows the fibers to go back together without any damage done. The board will get marked up over time with use, but wood will not be removed, as is the case sometimes with edge grain boards.

With that in mind, I think it would make sense to try and make it easy to select the end grain option quickly. Maybe a select all button type of deal. 

Might not be a bad idea to do that for wood type selection in the future as well.

**Comment by brian-slate** [comment]
I think that could just be an additional option for each strip, and yeah,
maybe an "all end grain/all edge grain" toggle button as well. We would
also need an "end grain" texture for each wood - or at the very least some
link to a library of what endgrains look like (theres a ticket to do a
popup highrez image gallery ticket in the backlog as well).

Is this something you'd like to work on?

**Comment by voltaaage** [comment]
Absolutely - I'll mock something up for the buttons probably tonight or tomorrow night and ask you guys for feedback when it's ready. I'm unclear on the textures and how to do that but I'll dig into it a bit and let you know if I need any help.

**Comment by brian-slate** [comment]
👍
