### ISSUE TITLE
Implement a modal system

### ISSUE THREAD

**Issue by trezy** [pcww/builder#66]
We need a modal system that we can use to show off zoomed images, as well as a loading animations for the initial load and order submission.

**Comment by voltaaage** [comment]
Is this mostly for the images in the wizard?

What's wrong with the current loading animation?

**Comment by brian-slate** [comment]
We need "pop-ups" for various things. One of which is the wizard images, and probably something for notifications and such.

**Comment by voltaaage** [comment]
@bmherold I probably should have clarified before going further down this path. I found a package that could be super useful called react-portal-tooltip but it's pretty similar to the tooltip package from react-bootstrap. 

Then I realized that you wanted a modal system which could be pretty different from what I was envisioning, which was to show a larger version of the images in the wizard, right next to it. Are you referring to an actual modal with faded background?

**Comment by trezy** [comment]
@voltaaage It'd be helpful if it was a dialog that could be used as either a dialog (non UI blocking) or a modal (UI blocking).

**Comment by voltaaage** [comment]
So use both [react-modal](https://github.com/reactjs/react-modal) and [react-portal-tooltip](https://github.com/romainberger/react-portal-tooltip) for the images in the wizard?

**Comment by brian-slate** [comment]
Main thing to start is to display images in a modal of each of the options in the wizard when clicking on the thumbnail.

**Comment by trezy** [comment]
It looks like react-modal is what we want.
