### ISSUE TITLE
Quick Orders

### ISSUE THREAD

**Issue by trezy** [pcww/builder#97]
1. "Buy this board” should be on every board image around the site
1. Clicking “Buy this board” should pop the user into the builder at the "Accessorize" step
    1. The builder should display the photo that the user came from

**Comment by trezy** [comment]
Dependent on #26

**Comment by brian-slate** [comment]
Jason said we can ignore this from an email tonight (10/13/2017). The 'cart' icon from the gallery should just take users to the shop and start a build for now.

**Comment by brian-slate** [comment]
Removing for now. Adding messaging to gallery to link user to store page to create a board. All the logic to do this is present, so we can work out the flows later when we know more.
